#tomcat
server.port=8082

#data source
spring.datasource.url=jdbc:mysql://bdcoti.mysql.database.azure.com:3306/bd_apiusuarios?serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=usuariojava
spring.datasource.password=Coti@2024

#jpa
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#jwt
jwt.secret=a22311c7-f5fc-47c7-b1f5-6932686c5166